apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hands-on
  name: hands-on
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hands-on
  strategy: {}
  template:
    metadata:
      namespace: user-12
      creationTimestamp: null
      labels:
        app: hands-on
        environment: "prod"
        version: "1.0.0"
    spec:
      containers:
      - image: nginx:latest
        name: foobar
        resources:
          requests:
            memory: "50Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        env:
          - name: DB_HOST
            value: "192.168.0.1"
          - name: DB_NAME
            value: "foobar"